$-l = false
$LOADED_FEATURES = ["enumerator.so", "etc.bundle", "fileutils.rb"]
$? = nil
$-F = nil
$-w = false
$: = ["/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/i686-darwin9.8.0", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby/1.8/i686-darwin9.8.0", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/i686-darwin9.8.0", "."]
$. = 1598
$KCODE = "NONE"
$* = ["/Users/youichikato/Documents/Titanium_Studio_Workspace/.metadata/.plugins/com.aptana.ruby.core/-394385121/4"]
$stderr = IO.new
$, = nil
$` = nil
$@ = nil
$fileutils_rb_have_lchown = nil
$-p = false
$" = ["enumerator.so", "etc.bundle", "fileutils.rb"]
$$ = 319
$< = ARGF
$; = nil
$-v = false
$-i = nil
$deferr = IO.new
$\ = nil
$= = false
$PROGRAM_NAME = "/Applications/Titanium Studio/configuration/org.eclipse.osgi/bundles/98/1/.cp/ruby/core_stubber.rb"
$stdout = IO.new
$& = nil
$-d = false
$LOAD_PATH = ["/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/i686-darwin9.8.0", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby/1.8/i686-darwin9.8.0", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/i686-darwin9.8.0", "."]
$-a = false
$VERBOSE = false
$FILENAME = "-"
$defout = IO.new
$-0 = "\n"
$+ = nil
$0 = "/Applications/Titanium Studio/configuration/org.eclipse.osgi/bundles/98/1/.cp/ruby/core_stubber.rb"
$stdin = IO.new
$~ = nil
$fileutils_rb_have_lchmod = nil
$DEBUG = false
$-I = ["/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby/1.8/i686-darwin9.8.0", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/site_ruby", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby/1.8/i686-darwin9.8.0", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/vendor_ruby", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8", "/Users/youichikato/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/i686-darwin9.8.0", "."]
$_ = nil
$-K = "NONE"
$> = IO.new
$/ = "\n"
$' = nil
$SAFE = 0
$! = nil
